# Data Handling

## Numerical Python - Numpy

In [1]:
import numpy as np

### Array creation  

In [2]:
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3]) #메모리 공간

numpy.float64

In [4]:
a = [1,2,3,4,5]
b = a
b[2] = 5
a  #b와 a는 같은 메모리 공간 사용

[1, 2, 5, 4, 5]

In [5]:
a = [[1,2,3,4],[3,4,5,6]]
b = a[:]     #메모리 주소만 카피
a[0][0] = 5
b

[[5, 2, 3, 4], [3, 4, 5, 6]]

In [6]:
test_array = np.array([1,4,5,"8"],float) #String Type의 데이터 입력

In [7]:
print(test_array)

[1. 4. 5. 8.]


In [8]:
print(type(test_array[3])) #Float Typed으로 자동 형변환을 실시

<class 'numpy.float64'>


In [9]:
print(test_array.dtype) #Array 전체의 데이터 Type을 반환

float64


In [10]:
print(test_array.shape) #Array의 shape을 반환함

(4,)


#### Array shape (matrix)  
- ndim - numer of dimension  
- size - 전체 data의 개수

In [11]:
vector  = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [12]:
matrix  = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [13]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape         #row의 사이즈는 맨 끝에 위치

(4, 3, 4)

In [14]:
np.array(tensor, int).ndim

3

In [15]:
np.array(tensor, int).size

48

#### Array dtype  
- nbytes - ndarray object의 메모리 크기를 반환함

In [16]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)

In [17]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [18]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float32).nbytes         #32bits = 4bytes , 6*4bytes = 24bytes

24

In [19]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.int8).nbytes

6

In [20]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float64).nbytes

48

### Numpy reshape

#### reshape  
- Array의 shape의 크기를 변경함(element의 갯수는 동일)  
- Array의 size만 같다면 다차원으로 자유로이 변형가능

In [21]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [22]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [23]:
test =np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [24]:
test.reshape(-1, 1)  # -1:size를 기반으로 row 개수 선정

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [25]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [26]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

In [27]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [28]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

#### flatten  or flat
- 다차원 array를 1차원 array로 변환

In [29]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

### indexing & slicing

#### indexing  
- List와 달리 이차원 배열에서 [0,0]과 같은 표기법을 제공함  
- Matrix 일경우 앞은 row 뒤는 column을 의미함

In [30]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
test_exmaple[0][0]

1

In [32]:
test_exmaple[0,0]

1

In [33]:
test_exmaple[0,0] = 12 # Matrix 0,0 에 12 할당
test_exmaple

array([[12,  2,  3],
       [ 4,  5,  6]])

In [34]:
test_exmaple[0][0] = 12 # Matrix 0,0 에 12 할당
test_exmaple[0,0]

12

#### slicing  
- List와 달리 행과 열 부분을 나눠서 slicing이 가능함  
- Matrix의 부분 집합을 추출할 때 유용함

In [35]:
test_exmaple = np.array([[1,2,5,8], [1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_exmaple[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [36]:
test_exmaple[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [37]:
test_exmaple[1,:2]

array([1, 2])

In [38]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [39]:
test_exmaple[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [40]:
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [41]:
a = np.arange(100).reshape(10,10)
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

### Numpy creation functions

#### arange  
- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [42]:
np.arange(30) #range: List의 range와 같은 효과, integer로 0부터 29까지 배열추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
np.arange(0, 5, 0.5) #floating point도 표시가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [44]:
np.arange(0, 5, 0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [45]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### ones, zeros, empty and something like 
- zeros: 0으로 가득찬 ndarray 생성  
- ones: 1로 가득찬 ndarray 생성  
- empty: shape만 주어지고 비어있는 ndarray 생성(memory initialization 이 되지 않음) 
- something like: 기존 ndarray의 shape 크기 만큼 1,0 또는 empty array를 반환 

In [46]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [47]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [49]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [51]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### identity, eye, digonal, random sampling
- identity: 단위 행렬(i 행렬)을 생성함  
- eye: 대각선인 1인 행렬, k값의 시작 index의 변경이 가능  
- diag: 대각 행렬의 값을 추출함  
- random sampling: 데이터 분포에 따른 sampling으로 array를 생성

In [53]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(3,5,k=2)  # k - start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [59]:
np.diag(matrix, k=1)

array([1, 5])

In [60]:
np.random.uniform(0,1,10).reshape(2,5)  #균등분포

array([[0.67781325, 0.70317251, 0.29912165, 0.92814077, 0.93608957],
       [0.22899723, 0.95311953, 0.84142124, 0.58412646, 0.7368785 ]])

In [61]:
np.random.normal(0,1,10).reshape(2,5)  #정규분포

array([[ 1.17180255, -0.24617765, -0.29677598,  0.12005467,  0.03385216],
       [-0.13842782,  1.25966949, -1.94866946,  0.59019371, -0.26482395]])

### ndarray operation functions

#### sum  
- ndarray의 element들 간의 합을 구함, list의 sum 기능과 동일

In [62]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
test_array.sum(dtype=np.float)

55.0

In [64]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum()

78

#### axis  
- 모든 operation function을 실행할 때, 기준이 되는 dimension 축

In [65]:
test_array.sum(axis=1) #column 기준, 기존에 존재하는 부분

array([10, 26, 42])

In [66]:
test_array.sum(axis=0) #row 기준, 새로 생기는 부분

array([15, 18, 21, 24])

In [67]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [68]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [69]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [70]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

#### mean & std  
- ndarray의 element들 간의 평균 또는 표준 편차를 반환

In [71]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [73]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [74]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

#### concatenate  
- Numpy array를 합치는 함수

In [75]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [76]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [77]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a,b.T) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [79]:
a.tolist()

[[1, 2], [3, 4]]

### array operations

#### Operations b/t arrays  
- numpy는 array간의 기본적인 사칙 연산을 지원함

In [80]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [81]:
test_a + test_a # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [82]:
test_a - test_a # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
test_a * test_a # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [84]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

#### Element-wise operations  
- Array간 shape이 같을 때 일어나는 연산

In [85]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

#### Dot product  
- Matrix의 기본 연산  
- dot 함수 사용

In [86]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [87]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

#### transpose  
- transpose 또는 T attribute 사용

In [88]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
test_a.T.dot(test_a) # Matrix 간 곱셈

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

#### broadcasting  
- Shape이 다른 배열 간 연산을 지원하는 기능

In [91]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [92]:
test_matrix + scalar # Matrix - Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [93]:
test_matrix - scalar # Matrix - Scalar 뺄셈

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [94]:
test_matrix * 5 # Matrix - Scalar 곱셈

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [95]:
test_matrix / 5 # Matrix - Scalar 나눗셈

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [96]:
test_matrix // 0.2 # Matrix - Scalar 몫

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [97]:
test_matrix ** 2 # Matrix - Scalar 제곱

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [98]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix+ test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### Comparion

#### All & Any  
- Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [99]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [101]:
np.any(a>5), np.any(a<0)

(True, False)

In [102]:
np.all(a>5) , np.all(a < 10)

(False, True)

#### comparision operation  
- Numpy는 배열의 크기가 동일 할 때 element간 비교의 결과를 Boolean type으로 반환하여 돌려줌  

In [103]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [104]:
test_a == test_b

array([False, False, False])

In [105]:
(test_a > test_b).any()

True

In [106]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False])

In [107]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False])

In [108]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

#### np.where 

In [109]:
a

array([1., 3., 0.])

In [110]:
np.where(a > 0, 3, 2)  #true일 경우 3, false일 경우  2

array([3, 3, 2])

In [111]:
np.where(a>0)  #index값 반환

(array([0, 1], dtype=int64),)

In [112]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [113]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [114]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [115]:
np.isfinite(a)

array([ True, False, False])

#### argmax & argmin  
- array내 최대값 또는 최소값의 index를 반환함  
- axis 기반의 반환

In [116]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)   #index 값

(5, 0)

In [117]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

### boolean & fancy index

#### boolean index  
- numpy는 배열은 특성 조건에 따른 값을 배열 형태로 추출 할 수 있음  
- Comparison operation 함수들도 모두 사용가능

In [118]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [119]:
test_array[test_array > 3]  #조건이 true인 index의 element만 추출

array([4., 8., 9., 7.])

In [120]:
condition = test_array < 3 
test_array[condition]

array([1., 0., 2.])

In [121]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

#### fancy index  
- numpy는 array를 index value로 사용해서 값을 추출하는 방법  
- matrix 형태의 데이터도 가능

In [126]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) #반드시 integer로 선언
a[b]

array([2., 2., 4., 8., 6., 4.])

In [127]:
a.take(b) #take 함수: bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [125]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

### numpy data i/o

#### loadtxt & savetxt  
- text type의 데이터를 읽고, 저장하는 기능

In [134]:
a = np.loadtxt("./populations.txt")
a[:9]

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [135]:
a_int = a.astype(int)
a_int[:3]

array([10, 20, 30])

In [136]:
np.savetxt('int_data.csv',a_int, delimiter=",")

#### numpy object - npy  
- Numpy object(pickle) 형태로 데이터를 저장하고 불러옴  
- Binary 파일 형태로 저장함

In [137]:
np.save("npy_test", arr=a_int)

In [138]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([10, 20, 30])